"""add new fields in user table

Revision ID: 275b21efa602
Revises: 93743745df3e
Create Date: 2021-02-15 17:58:30.764652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275b21efa602'
down_revision = '93743745df3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
